Repository Topkinsme/Color-Battle-Roles, pull requests merged in 2021-08, with the labels that each got.

#64 Update bomber
  killing/bomber
Labels: enhancement, issue

#63 Potion master 3rd potion patch
  crafting/potion_master
Labels: enhancement

#67 Create jack
  royalty/jack
Labels: enhancement

#65 Issue Fixes for original Jester role [Jester -> Escort]
  categories/Strong_Power
  strong_power/escort
Labels: issue, enhancement

#69 Update Auction
  _info/Auction
  _info/Black_market
  _info/Blind_auction
  _info/Conspiracy_Channels
  _info/Forge
  _info/Market
  _info/Office
  _info/Stash
  _info/Stock_market
  _info/Tribute
  _info/Vault
Labels: issue, clarifications
